---
logs:
  prefix: ''
  console:
    active: true
    level: info
    colorize: true
  file:
    active: false
email:
  message:
    from:
      name: Your Email address
      address: change@my.email
  preview: false  # If true, it will open a webpage with a preview
  send: true # Activate/deactivate the actual sending (prod/test env)
# Alternative transport, using the sendmail command of the machine
sendmail:
  active: true # Set to false to use SMTP transport
  path: "/usr/sbin/sendmail"
smtp:
  host: smtp.email.service
  port: 587
  # Credentials to authenticate against SMTP server
  auth:
    user: change@my.email
    pass: YourPassword
http:
  ip: 127.0.0.1 # IP address on which the mailing server is listening
  port: 9000 
  # Each sendmail request should contain authorization header that
  # matches this key, used to prevent abuse.
  # No need to change if ip adress is not facing the internet.
  auth: SHOULD_MATCH_SERVICE_MAIL
templates:
  root: "./templates/"
  defaultLang: en
