---
logs:
  console:
    active: true
http:
  auth: prZ9WM1!p_QASy^kG%9tGPYQhTTKy)wS#Zt(Fv%cHD4O7XJfPx4K*9080ulr2^jA
smtp:
  host: smtp.sendgrid.net,
  auth:
    user: apikey,
    pass: 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
