name: Service mail CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run-tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.4]

    steps:
    - name: Install `just`
      uses: extractions/setup-just@v1

    - name: Download master branch
      uses: actions/checkout@v2

    - name: Install Node.js with version ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: just install-stable

    - name: Run tests
      run: IS_CI=true just test
